const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const aiRoutes = require('./ai.routes');
const userRoutes = require('./user.routes');
const productRoutes = require('./product.routes');
const invitationRoutes = require('./invitation.routes');
const invitationTemplateRoutes = require('./invitationTemplate.routes');
const designAssetRoutes = require('./designAsset.routes');
const pageRoutes = require('./page.routes');
const masterGuestRoutes = require('./masterGuest.routes.js');
const fontRoutes = require('./font.routes');
const pageCategoryRoutes = require('./pageCategory.routes');
const publicRoutes = require('./public.routes');
const mapRoutes = require('./map.routes'); 
const wishRoutes = require('./wish.routes');
router.use('/wishes', wishRoutes);
router.use('/auth', authRoutes);
router.use('/ai', aiRoutes);
router.use('/users', userRoutes);
router.use('/products', productRoutes);
router.use('/invitations', invitationRoutes);
router.use('/invitation-templates', invitationTemplateRoutes);
router.use('/design-assets', designAssetRoutes);
router.use('/pages', pageRoutes);
router.use('/master-guests', masterGuestRoutes);
router.use('/fonts', fontRoutes);
router.use('/page-categories', pageCategoryRoutes);
router.use('/public', publicRoutes);
router.use('/maps', mapRoutes);
module.exports = router;